### ISSUE TITLE
qq红包助手无反应，xposed日志报错

### ISSUE THREAD

**Issue by vito16** [veryyoung/QQLuckyMoney#36]
```
01-10 00:31:44.198 E/Xposed  (13193): java.lang.NoSuchFieldError: com.tencent.mobileqq.data.QQWalletRedPacketMsg#redChannel
01-10 00:31:44.198 E/Xposed  (13193): 	at de.robv.android.xposed.XposedHelpers.findField(XposedHelpers.java:96)
01-10 00:31:44.198 E/Xposed  (13193): 	at de.robv.android.xposed.XposedHelpers.getObjectField(XposedHelpers.java:850)
01-10 00:31:44.198 E/Xposed  (13193): 	at me.veryyoung.qq.luckymoney.Main$1.afterHookedMethod(Unknown Source)
01-10 00:31:44.198 E/Xposed  (13193): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:1588)
01-10 00:31:44.198 E/Xposed  (13193): 	at com.tencent.mobileqq.data.MessageForQQWalletMsg.doParse(<Xposed>)
01-10 00:31:44.198 E/Xposed  (13193): 	at com.tencent.mobileqq.data.ChatMessage.parse(ProGuard:64)
01-10 00:31:44.198 E/Xposed  (13193): 	at com.tencent.mobileqq.app.message.BaseMessageManager.a(ProGuard:1198)
01-10 00:31:44.198 E/Xposed  (13193): 	at com.tencent.mobileqq.app.message.QQMessageFacade.a(ProGuard:1735)
01-10 00:31:44.198 E/Xposed  (13193): 	at com.tencent.mobileqq.app.message.QQMessageFacade.a(ProGuard:959)
01-10 00:31:44.198 E/Xposed  (13193): 	at com.tencent.mobileqq.app.message.QQMessageFacade.a(ProGuard:789)
01-10 00:31:44.198 E/Xposed  (13193): 	at com.tencent.mobileqq.app.message.C2CMessageProcessor.a(ProGuard:1214)
01-10 00:31:44.198 E/Xposed  (13193): 	at com.tencent.mobileqq.app.message.C2CMessageProcessor.a(ProGuard:1690)
01-10 00:31:44.198 E/Xposed  (13193): 	at com.tencent.mobileqq.app.message.C2CMessageProcessor.a(ProGuard:191)
01-10 00:31:44.198 E/Xposed  (13193): 	at com.tencent.mobileqq.app.MessageHandler.a(ProGuard:3438)
01-10 00:31:44.198 E/Xposed  (13193): 	at com.tencent.mobileqq.service.MobileQQServiceBase.a(ProGuard:309)
01-10 00:31:44.198 E/Xposed  (13193): 	at com.tencent.mobileqq.service.MobileQQService.a(ProGuard:658)
01-10 00:31:44.198 E/Xposed  (13193): 	at com.tencent.mobileqq.app.QQAppInterface.a(ProGuard:8998)
01-10 00:31:44.198 E/Xposed  (13193): 	at com.tencent.mobileqq.compatible.TempServlet.onReceive(ProGuard:52)
01-10 00:31:44.198 E/Xposed  (13193): 	at mqq.app.MSFServlet.onReceive(MSFServlet.java:39)
01-10 00:31:44.198 E/Xposed  (13193): 	at mqq.app.ServletContainer.notifyMSFServlet(ServletContainer.java:115)
01-10 00:31:44.198 E/Xposed  (13193): 	at mqq.app.MainService.receiveMessageFromMSF(MainService.java:261)
01-10 00:31:44.198 E/Xposed  (13193): 	at mqq.app.MainService.access$300(MainService.java:67)
01-10 00:31:44.198 E/Xposed  (13193): 	at mqq.app.MainService$4.onRecvResp(MainService.java:818)
01-10 00:31:44.198 E/Xposed  (13193): 	at com.tencent.mobileqq.msf.sdk.MsfRespHandleUtil.handleRespMsg(MsfRespHandleUtil.java:568)
01-10 00:31:44.198 E/Xposed  (13193): 	at mqq.app.MainService$2.handleResp(MainService.java:507)
01-10 00:31:44.198 E/Xposed  (13193): 	at mqq.app.MainService$2.run(MainService.java:470)
01-10 00:31:44.198 E/Xposed  (13193): 	at java.lang.Thread.run(Thread.java:818)
01-10 00:31:56.568 I/Xposed  (15980): Found QQ version:6.6.2
01-10 00:31:58.938 I/Xposed  (13193): Hid package: de.robv.android.xposed.installer
01-10 00:31:58.938 I/Xposed  (13193): Hid package: me.veryyoung.qq.luckymoney
```

xposed后台报错信息。  
是什么情况啊？？

QQ版本：6.6.2  
插件版本：1.0.9

**Comment by jpacg** [comment]
请使用最新的代码编译，新代码修复了。

**Comment by veryyoung** [comment]
@jpacg   我昨天测试了 6.6.6，旧代码 work

**Comment by jpacg** [comment]
@veryyoung 额，不好意思，昨天测试不完全，刚刚解包看到6.6.6还是有redChannel的，但6.6.2确实没有这个的，但我改成channelId在6.6.6可以抢红包，不知道有没有影响。


```
版本6.6.6
# instance fields
.field public authkey:Ljava/lang/String;
.field private channelId:I
.field public conftype:I
.field public elem:Lcom/tencent/mobileqq/data/QQWalletTransferMsgElem;
.field public envelopeName:Ljava/lang/String;
.field public envelopeid:I
.field public isOpened:Z
.field public msgFrom:I
.field public redChannel:I
.field public redPacketId:Ljava/lang/String;
.field public redPacketIndex:Ljava/lang/String;
.field public redtype:I
.field private resend:I
.field public specifyUinList:Ljava/util/List;
.field public templateId:I

版本6.6.2
# instance fields
.field public authkey:Ljava/lang/String;
.field private channelId:I
.field public conftype:I
.field public elem:Lcom/tencent/mobileqq/data/QQWalletTransferMsgElem;
.field public envelopeName:Ljava/lang/String;
.field public envelopeid:I
.field public isOpened:Z
.field public msgFrom:I
.field public redPacketId:Ljava/lang/String;
.field public redPacketIndex:Ljava/lang/String;
.field public redtype:I
.field private resend:I
.field public templateId:I
```

**Comment by vito16** [comment]
@veryyoung @jpacg 感谢二位，升级了6.6.6，确实成功了，谢谢。
