### ISSUE TITLE
1.1.2，一打开FC

### ISSUE THREAD

**Issue by sanxiaozhizi** [veryyoung/QQLuckyMoney#60]
MIUI 8，小米4，android 6
错误日志：
java.lang.RuntimeException: Unable to start activity ComponentInfo{me.veryyoung.qq.luckymoney/me.veryyoung.qq.luckymoney.SettingsActivity}: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2436)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2496)
	at android.app.ActivityThread.access$1000(ActivityThread.java:153)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1362)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5457)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
Caused by: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
	at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:225)
	at android.preference.Preference.getPersistedString(Preference.java:1472)
	at android.preference.ListPreference.onSetInitialValue(ListPreference.java:295)
	at android.preference.Preference.dispatchSetInitialValue(Preference.java:1388)
	at android.preference.Preference.onAttachedToHierarchy(Preference.java:1182)
	at android.preference.PreferenceGroup.addPreference(PreferenceGroup.java:164)
	at android.preference.PreferenceGroup.addItemFromInflater(PreferenceGroup.java:105)
	at android.preference.PreferenceGroup.addItemFromInflater(PreferenceGroup.java:42)
	at android.preference.GenericInflater.rInflate(GenericInflater.java:490)
	at android.preference.GenericInflater.rInflate(GenericInflater.java:495)
	at android.preference.GenericInflater.inflate(GenericInflater.java:327)
	at android.preference.GenericInflater.inflate(GenericInflater.java:264)
	at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:273)
	at android.preference.PreferenceFragment.addPreferencesFromResource(PreferenceFragment.java:301)
	at me.veryyoung.qq.luckymoney.SettingsActivity$SettingsFragment.onCreate(Unknown Source)
	at android.app.Fragment.performCreate(Fragment.java:2198)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:942)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
	at android.app.BackStackRecord.run(BackStackRecord.java:799)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1537)
	at android.app.FragmentController.execPendingActions(FragmentController.java:325)
	at android.app.Activity.performStart(Activity.java:6319)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2399)
	... 10 more

**Comment by sinntd** [comment]
楼主之前miui8能用吗？我也是miui，但是是安卓5.1，一直用不了

**Comment by veryyoung** [comment]
@sanxiaozhizi https://github.com/veryyoung/QQLuckyMoney/issues/57
