### ISSUE TITLE
com.tenpay.android.qqplugin.c.d类无法找到

### ISSUE THREAD

**Issue by DLDarwin** [veryyoung/QQLuckyMoney#79]
使用这个红包插件的时候出现了如下问题，我的红米4x手机，安卓系统版本：6.0.1，MIUI版本：8.7.4.27
 qq版本试了6.6.5和6.7.1，都不行，不知道为什么， @lintuhua  希望帮忙看看。多谢

xposed日志信息如下所示：
05-03 22:08:01.410 I/Xposed  ( 5084): Hid package: de.robv.android.xposed.installer
05-03 22:08:01.411 I/Xposed  ( 5084): Hid package: me.veryyoung.qq.luckymoney
05-03 22:08:01.411 I/Xposed  ( 5084): Hid package: com.zjns.xposedinstaller
05-03 22:08:28.648 E/Xposed  ( 5084): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.tenpay.android.qqplugin.c.d
05-03 22:08:28.648 E/Xposed  ( 5084): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:68)
05-03 22:08:28.648 E/Xposed  ( 5084): 	at me.veryyoung.qq.luckymoney.Main$1.afterHookedMethod(Main.java:157)
05-03 22:08:28.648 E/Xposed  ( 5084): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:348)
05-03 22:08:28.648 E/Xposed  ( 5084): 	at com.tencent.mobileqq.data.MessageForQQWalletMsg.doParse(<Xposed>)
05-03 22:08:28.648 E/Xposed  ( 5084): 	at com.tencent.mobileqq.data.ChatMessage.parse(ProGuard:64)
05-03 22:08:28.648 E/Xposed  ( 5084): 	at com.tencent.mobileqq.app.message.BaseMessageManager.a(ProGuard:1198)
05-03 22:08:28.648 E/Xposed  ( 5084): 	at com.tencent.mobileqq.app.message.QQMessageFacade.a(ProGuard:1744)
05-03 22:08:28.648 E/Xposed  ( 5084): 	at com.tencent.mobileqq.app.message.QQMessageFacade.a(ProGuard:962)
05-03 22:08:28.648 E/Xposed  ( 5084): 	at com.tencent.mobileqq.app.message.QQMessageFacade.a(ProGuard:792)
05-03 22:08:28.648 E/Xposed  ( 5084): 	at com.tencent.mobileqq.app.message.DiscMessageProcessor.a(ProGuard:1982)
05-03 22:08:28.648 E/Xposed  ( 5084): 	at com.tencent.mobileqq.app.message.DiscMessageProcessor.a(ProGuard:294)
05-03 22:08:28.648 E/Xposed  ( 5084): 	at com.tencent.mobileqq.app.MessageHandler.h(ProGuard:2426)
05-03 22:08:28.648 E/Xposed  ( 5084): 	at com.tencent.mobileqq.app.MessageHandler.a(ProGuard:3875)
05-03 22:08:28.648 E/Xposed  ( 5084): 	at com.tencent.mobileqq.service.MobileQQServiceBase.a(ProGuard:309)
05-03 22:08:28.648 E/Xposed  ( 5084): 	at com.tencent.mobileqq.service.MobileQQService.a(ProGuard:658)
05-03 22:08:28.648 E/Xposed  ( 5084): 	at com.tencent.mobileqq.app.QQAppInterface.a(ProGuard:9047)
05-03 22:08:28.648 E/Xposed  ( 5084): 	at com.tencent.mobileqq.compatible.TempServlet.onReceive(ProGuard:52)
05-03 22:08:28.648 E/Xposed  ( 5084): 	at mqq.app.MSFServlet.onReceive(MSFServlet.java:39)
05-03 22:08:28.648 E/Xposed  ( 5084): 	at mqq.app.ServletContainer.notifyMSFServlet(ServletContainer.java:125)
05-03 22:08:28.648 E/Xposed  ( 5084): 	at mqq.app.MainService.receiveMessageFromMSF(MainService.java:261)
05-03 22:08:28.648 E/Xposed  ( 5084): 	at mqq.app.MainService.access$300(MainService.java:67)
05-03 22:08:28.648 E/Xposed  ( 5084): 	at mqq.app.MainService$5.onRecvCmdPush(MainService.java:830)
05-03 22:08:28.648 E/Xposed  ( 5084): 	at com.tencent.mobileqq.msf.sdk.MsfRespHandleUtil.handlePushMsg(MsfRespHandleUtil.java:186)
05-03 22:08:28.648 E/Xposed  ( 5084): 	at mqq.app.MainService$2.run(MainService.java:459)
05-03 22:08:28.648 E/Xposed  ( 5084): 	at java.lang.Thread.run(Thread.java:818)
05-03 22:08:28.648 E/Xposed  ( 5084): Caused by: java.lang.ClassNotFoundException: com.tenpay.android.qqplugin.c.d
05-03 22:08:28.648 E/Xposed  ( 5084): 	at java.lang.Class.classForName(Native Method)
05-03 22:08:28.648 E/Xposed  ( 5084): 	at java.lang.Class.forName(Class.java:324)
05-03 22:08:28.648 E/Xposed  ( 5084): 	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
05-03 22:08:28.648 E/Xposed  ( 5084): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:66)
05-03 22:08:28.648 E/Xposed  ( 5084): 	... 24 more
05-03 22:08:28.648 E/Xposed  ( 5084): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tenpay.android.qqplugin.c.d" on path: DexPathList[[zip file "/data/data/com.tencent.mobileqq/app_installed_plugin/qwallet_plugin.apk"],nativeLibraryDirectories=[/data/data/com.tencent.mobileqq/app_lib/qwallet_plugin, /vendor/lib, /system/lib]]
05-03 22:08:28.648 E/Xposed  ( 5084): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05-03 22:08:28.648 E/Xposed  ( 5084): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
05-03 22:08:28.648 E/Xposed  ( 5084): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
05-03 22:08:28.648 E/Xposed  ( 5084): 	... 28 more
05-03 22:08:28.648 E/Xposed  ( 5084): 	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.tenpay.android.qqplugin.c.d" on path: DexPathList[[zip file "/data/app/com.tencent.mobileqq-1/base.apk"],nativeLibraryDirectories=[/data/app/com.tencent.mobileqq-1/lib/arm, /data/app/com.tencent.mobileqq-1/base.apk!/lib/armeabi, /vendor/lib, /system/lib]]
05-03 22:08:28.648 E/Xposed  ( 5084): 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05-03 22:08:28.648 E/Xposed  ( 5084): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
05-03 22:08:28.648 E/Xposed  ( 5084): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
05-03 22:08:28.648 E/Xposed  ( 5084): 		... 29 more
05-03 22:08:28.648 E/Xposed  ( 5084): 		Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.tenpay.android.qqplugin.c.d" on path: DexPathList[[dex file "/data/dalvik-cache/xposed_XResourcesSuperClass.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
05-03 22:08:28.648 E/Xposed  ( 5084): 			at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05-03 22:08:28.648 E/Xposed  ( 5084): 			at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
05-03 22:08:28.648 E/Xposed  ( 5084): 			at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
05-03 22:08:28.648 E/Xposed  ( 5084): 			... 30 more
05-03 22:08:28.648 E/Xposed  ( 5084): 			Suppressed: java.lang.ClassNotFoundException: com.tenpay.android.qqplugin.c.d
05-03 22:08:28.648 E/Xposed  ( 5084): 				at java.lang.Class.classForName(Native Method)
05-03 22:08:28.648 E/Xposed  ( 5084): 				at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
05-03 22:08:28.648 E/Xposed  ( 5084): 				at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
05-03 22:08:28.648 E/Xposed  ( 5084): 				at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
05-03 22:08:28.648 E/Xposed  ( 5084): 				... 31 more

**Comment by DLDarwin** [comment]
已解决，应该是关闭了太多qq应用权限的问题
